const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
  const base = process.env.PW_QA_URL || 'http://127.0.0.1:8766/';
  const browser = await chromium.launch({...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {}),headless:true});
  try {
    const context = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
    const page = await context.newPage();
    const errors = []; page.on('pageerror',e=>errors.push(e.message));
    await page.goto(base+'index.html');
    await page.getByRole('tab',{name:'2 — Policy lab & framing'}).click();
    assert.equal(await page.locator('#panel-lab').isVisible(),true);
    await page.getByRole('link',{name:'3 — When is evidence worth waiting for?'}).click();
    await page.locator('#policy-value').getByText('17.5',{exact:true}).waitFor();
    assert.equal(await page.locator('#commit-value').innerText(),'15');
    assert.equal(await page.locator('#gross').innerText(),'9.5 points');
    assert.match(await page.locator('#usable-caption').innerText(),/Net gain vs commit-now: 2.5 points/);
    assert.equal(await page.locator('#paths tr').count(),2);
    assert.match(await page.locator('#form-status').innerText(),/No programme changes or file created/);
    assert.match(page.url(),/prior=0.5/);
    assert.equal(await page.locator('#policy-map [data-follow-signal]').count(),2);
    assert.match(await page.locator('#value-caption').innerText(),/15 \+ 9.5 − 4 − 3 = 17.5/);
    assert.match(await page.locator('#timing-caption').innerText(),/before day 2/);
    await page.locator('#policy-map [data-follow-signal="+"]').focus();
    await page.keyboard.press('Enter');
    assert.match(await page.locator('#policy-map').innerText(),/Reserve three buses/);
    assert.match(await page.locator('#node-heading').innerText(),/Review 1.*80%/);
    assert.equal(await page.locator('#visual-reset').evaluate(el=>el===document.activeElement),true);
    await page.locator('#visual-reset').click();
    await page.locator('#policy-map [data-follow-signal="-"]').click();
    assert.match(await page.locator('#policy-map').innerText(),/Reserve one bus/);
    await page.locator('#visual-reset').click();
    const positive=page.locator('#branch-inspector [data-signal="+"]'); await positive.focus(); await page.keyboard.press('Enter');
    assert.match(await page.locator('#node-heading').innerText(),/Review 1.*80%/);
    assert.match(await page.locator('#branch-inspector').innerText(),/Reserve the three-bus fleet/);
    await page.getByRole('button',{name:'Back to review 0'}).click();
    await page.locator('#branch-inspector [data-signal="-"]').click();
    assert.match(await page.locator('#branch-inspector').innerText(),/Reserve one shuttle bus/);
    await page.locator('[data-preset="unchanged"]').click();
    assert.equal(await page.locator('#policy-value').innerText(),'55');
    assert.equal(await page.locator('#gross').innerText(),'0 points');
    assert.match(await page.locator('#difference-copy').innerText(),/same scope choice/);
    await page.locator('[data-preset="late"]').click();
    assert.equal(await page.locator('#policy-value').innerText(),'15');
    assert.equal(await page.locator('#usable').innerText(),'0 points');
    assert.match(await page.locator('#timeline').innerText(),/too late/);
    assert.match(await page.locator('#value-caption').innerText(),/No evidence costs are paid/);
    assert.match(await page.locator('#alternatives').innerText(),/Unavailable/);
    await page.locator('[data-preset="routine"]').click();
    assert.equal(await page.locator('#policy-value').innerText(),'21.5');
    assert.equal(await page.locator('#verdict-title').innerText(),'Wait for fresh booking counts');
    await page.locator('[data-preset="sequential"]').click();
    assert.equal(await page.locator('#policy-value').innerText(),'21.44');
    assert.equal(await page.locator('#paths tr').count(),6);
    await page.locator('[data-preset="nonmyopic"]').click();
    assert.equal(await page.locator('#policy-value').innerText(),'12.04');
    assert.equal(await page.locator('#gross').innerText(),'0 points');
    assert.match(await page.locator('#difference-copy').innerText(),/Zero one-test value does not mean zero sequential value/);
    assert.match(await page.locator('#visual-lesson').innerText(),/changes whether another test/);
    await page.locator('#policy-map [data-follow-signal="+"]').click();
    assert.match(await page.locator('#policy-map .policy-node').innerText(),/Buy a fresh survey/);
    await page.locator('#policy-map [data-follow-signal="+"]').click();
    assert.match(await page.locator('#policy-map .policy-node').innerText(),/Reserve three buses/);
    await page.locator('#visual-reset').click();
    await page.locator('#branch-inspector [data-signal="+"]').click();
    assert.match(await page.locator('#branch-inspector h3').innerText(),/Commission a demand survey/);
    await page.reload();
    assert.equal(await page.locator('#policy-value').innerText(),'12.04');
    assert.match(await page.locator('#node-heading').innerText(),/Review 0/);
    await page.locator('#prior').fill('2');
    assert.match(await page.locator('#form-status').innerText(),/not yet applied/);
    await page.getByRole('button',{name:'Recalculate experiment'}).click();
    assert.equal(await page.locator('#form-error').isVisible(),true);
    assert.equal(await page.locator('#prior').inputValue(),'2');
    assert.equal(await page.locator('#policy-value').innerText(),'12.04');
    await page.locator('#prior').fill('0.5');
    await page.getByRole('button',{name:'Recalculate experiment'}).click();
    assert.equal(await page.locator('#form-error').isVisible(),false);
    assert.match(page.url(),/prior=0.5/);
    await page.reload(); assert.equal(await page.locator('#prior').inputValue(),'0.5');
    await page.goto(base+'evidence.html?prior=oops');
    assert.match(await page.locator('#form-status').innerText(),/invalid settings/);
    assert.equal(await page.locator('#policy-value').innerText(),'17.5');
    await page.goto(base+'evidence.html?accuracy=0.5&passive=0.8');
    assert.equal(await page.locator('#policy-value').innerText(),'21.5');
    assert.match(await page.locator('#difference-copy').innerText(),/Another evidence route/);
    assert.doesNotMatch(await page.locator('#difference-copy').innerText(),/chosen test-first policy/);
    await page.locator('#prior').fill('');
    await page.getByRole('button',{name:'Recalculate experiment'}).click();
    assert.equal(await page.locator('#form-error').isVisible(),true);
    await page.getByRole('button',{name:'Reset to the first experiment'}).click();
    assert.equal(await page.locator('#prior').inputValue(),'0.5');
    await page.evaluate(()=>scrollTo(0,0));
    await page.locator('.visual-essay').screenshot({path:require('node:path').join(require('node:os').tmpdir(),'pw-220-visual-desktop.png')});
    for(const width of [360,390,768,1440]) {
      await page.setViewportSize({width,height:900});
      for(const preset of ['timely','unchanged','late','routine','sequential','nonmyopic']) {
        await page.locator(`[data-preset="${preset}"]`).click();
        assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,`${width} overflow ${preset}`);
      }
    }
    await page.setViewportSize({width:390,height:844});
    await page.locator('[data-preset="timely"]').click();
    await page.evaluate(()=>scrollTo(0,0));
    await page.locator('.visual-essay').screenshot({path:require('node:path').join(require('node:os').tmpdir(),'pw-220-visual-mobile.png')});
    await page.locator('#model-notes summary').click();
    await page.locator('#sources summary').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'open details mobile overflow');
    for(const file of ['evidence-model.js','evidence-visuals.js','evidence-ui.js','evidence.css','EVIDENCE_METHOD.md']) assert.equal((await page.request.get(base+file)).status(),200,file);
    await page.getByRole('link',{name:'← Sequence, belief & policy lab'}).click();
    assert.equal(await page.locator('#panel-sequence').isVisible(),true);
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({result:'PASS',base,checks:['six exact witnesses','visual policy branch and reset','keyboard focus after terminal choice','value bridge and timing','nonmyopic visual route','all policy paths','home and both original tabs retained','URL persistence and reload','invalid input preserves entries and prior result','correction and reset','malformed URL recovery','360/390/768/1440 layout','public asset routes','no runtime errors']},null,2));
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
